# Action to manually set the next development version
---
name: "Maven: Set Next Development Version"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      next_version:
        description: "Set the next development version"
        required: true
        default: ""

env:
  JAVA_VERSION: "17"
  JAVA_DISTRIBUTION: "corretto"
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Djava.awt.headless=true"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check release ends with snapshot
        if: ${{ !endsWith(github.event.inputs.next_version, '-SNAPSHOT') }}
        run: |
          echo "Invalid input: next development version ${{ github.event.inputs.next_version }} does not end with '-SNAPSHOT'"
          exit 1
  snapshot-bump:
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: "maven"

      - name: Configure Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Set the name of the branch
        run: echo "PR_BRANCH=action/${{ github.event.inputs.next_version }}" >> "$GITHUB_ENV"

      - name: Create a branch
        run: git switch -c ${{ env.PR_BRANCH }}

      - name: Set the next snapshot version
        run: |
          mvn -B -V -e -ntp versions:set -DnewVersion=${{ github.event.inputs.next_version }} -DgenerateBackupPoms=false
          mvn -B -V -e -ntp versions:commit
          git add .
          git commit -m "[github-actions](${{ github.actor }}) next development iteration"
          git push -u origin ${{ env.PR_BRANCH }}

      - name: Create pull request
        run: gh pr create -B main -H ${{ env.PR_BRANCH }} --title 'next development iteration ${{ github.event.inputs.next_version }}' --body 'Created by GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
